apiVersion: v1
kind: Service
metadata:
  name: {{ include "kad.fullname" . }}-agent-sdk-rest-server
  labels:
    {{- include "kad.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.sdkRestServer.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
