apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kad.fullname" . }}-agent
  labels:
    {{- include "kad.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kad.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kad.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /status
          #     port: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: TEMPORAL_SERVICE_URL
              value: "{{ .Values.temporal.temporalServiceURL }}.{{ .Release.Namespace }}.svc.cluster.local:7233"
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: VAULT_ADDR
              value: {{ .Values.vault.address }}
            - name: VAULT_CRED_ADDR
              value: {{ .Values.vaultCred.address }}
            - name: DOMAIN_NAME
              value: {{ .Values.DomainName }}
            - name: VAULT_ROLE
              value: {{ .Values.vault.role }}
            - name: PG_DB_HOST
              value: {{ .Values.postgres.host }}
            - name: PG_DB_PORT
              value: {{ .Values.postgres.port }}
            - name: PG_DB_SERVICE_USERNAME
              value: {{ .Values.postgres.userName }}
            - name: PG_DB_ENTITY_NAME
              value: {{ .Values.postgres.entityName }}
            - name: PG_DB_NAME
              value: {{ .Values.cassandra.dbName }}
            - name: AGENT_CLUSTER_CA_ISSUER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kad-agent-config
                  key: clusterIssuerName
              value: {{ .Values.postgres.dbName }}
            - name: PG_DB_ADMIN_CRED_IDENTIFIER 
              value: {{ .Values.postgres.adminCredIdentifer }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
