apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kad.fullname" . }}-deployment-worker
  labels:
    {{- include "kad.labels" . | nindent 4 }}
    app.kubernetes.io/component: deployment-worker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deployment-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kad.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: deployment-worker
    spec:
      serviceAccountName: {{ include "kad.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-deployment-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.deployment_worker.repository }}:{{ .Values.image.deployment_worker.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel }}
            - name: TEMPORAL_SERVICE_URL
              value: "{{ .Values.temporal.temporalServiceURL }}.{{ .Release.Namespace }}.svc.cluster.local:7233"
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: HOME
              value: /tmp
            - name: VAULT_ADDR
              value: {{ .Values.vault.address }}
            - name: VAULT_CRED_ADDR
              value: {{ .Values.vaultCred.address }}
            - name: DOMAIN_NAME
              value: {{ .Values.DomainName }}
            - name: VAULT_ROLE
              value: {{ .Values.vault.role }}
            - name: PG_DB_HOST
              value: {{ .Values.postgres.host }}
            - name: PG_DB_PORT
              value: {{ .Values.postgres.port }}
            - name: PG_DB_SERVICE_USERNAME
              value: {{ .Values.postgres.userName }}
            - name: PG_DB_ENTITY_NAME
              value: {{ .Values.postgres.entityName }}
            - name: PG_DB_NAME
              value: {{ .Values.cassandra.dbName }}
            - name: AGENT_ADDRESSES
              value: {{ include "kad.fullname" . }}-agent
            - name: AGENT_CLUSTER_CA_ISSUER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kad-agent-config
                  key: clusterIssuerName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
